name: "シナリオ (Scenario)"
description: "要求に対して利用者が目的を達成する流れを記述する"
title: "シナリオ: "
labels: ["シナリオ"]
body:
  - type: markdown
    attributes:
      value: "📖 全体像や必須ルールの詳細は [docs/README.md](docs/README.md) を参照してください。"
  - type: input
    id: actor
    attributes:
      label: アクター
      description: このシナリオに登場するアクター
  - type: input
    id: goal
    attributes:
      label: ゴール
      description: シナリオの目的
  - type: textarea
    id: flow
    attributes:
      label: フロー
      description: 代表的な手順
  - type: textarea
    id: acceptance
    attributes:
      label: 受入基準
      description: 検証可能な観測指標を記述

